SHENV_ROOT=${SHENV_ROOT:-$HOME/.shenv}

if [ -f "$SHENV_ROOT"/path.sh ]; then
  source "$SHENV_ROOT"/path.sh
fi

share_dir="$SHENV_ROOT"/share
modules=($(ls "$share_dir"))

for module in "${modules[@]}"; do
  module_dir="$share_dir/$module"
  stuffs=($(ls "$module_dir"))
  for file in "${stuffs[@]}"; do
    source "$module_dir/$file"
  done
done

if [ "$(which brew)" ]; then
  if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    source "$(brew --prefix)/etc/bash_completion"
  fi
fi

